// NexCore -- Nexflow Codegen: Java Builder Generator
// Copyright (c) 2024-2026 Chandra Mohn. All Rights Reserved.

//! Generates `*Builder.java` classes for Avro SpecificRecord schemas.
//!
//! Since Avro `SpecificRecord` classes are generated by the Maven plugin
//! from `.avsc` files, these builders provide a fluent API on top.
//! They use the Avro `newBuilder()` / `build()` pattern internally.

use std::fmt::Write;

use nexflow_parser::ast::schema::{FieldDecl, SchemaDefinition};

use super::naming::{to_camel_case, to_pascal_case};
use super::types::java_type;

const DEFAULT_PACKAGE: &str = "com.nexflow.schemas";

/// Generate a Builder Java class for the given schema.
///
/// Returns `(filename, content)`.
pub fn generate_builder(schema: &SchemaDefinition) -> (String, String) {
    let class_name = to_pascal_case(&schema.name);
    let builder_name = format!("{class_name}Builder");
    let all_fields = collect_all_fields(schema);
    let filename = format!("{builder_name}.java");

    let mut out = String::with_capacity(4096);

    // Package and imports
    writeln!(out, "package {DEFAULT_PACKAGE};").unwrap();
    writeln!(out).unwrap();
    write_imports(&mut out, &all_fields);
    writeln!(out).unwrap();

    // Class header
    writeln!(out, "/**").unwrap();
    writeln!(
        out,
        " * Fluent builder for {{@link {class_name}}} Avro records."
    )
    .unwrap();
    writeln!(out, " * Generated from {}.schema -- DO NOT EDIT.", schema.name).unwrap();
    writeln!(out, " */").unwrap();
    writeln!(out, "public final class {builder_name} {{").unwrap();
    writeln!(out).unwrap();

    // Fields
    for f in &all_fields {
        let java_t = java_type(&f.field_type);
        let java_name = to_camel_case(&f.name);
        writeln!(out, "    private {java_t} {java_name};").unwrap();
    }
    writeln!(out).unwrap();

    // Private constructor
    writeln!(out, "    private {builder_name}() {{}}").unwrap();
    writeln!(out).unwrap();

    // Static factory: builder()
    writeln!(out, "    /**").unwrap();
    writeln!(out, "     * Create a new empty builder.").unwrap();
    writeln!(out, "     */").unwrap();
    writeln!(out, "    public static {builder_name} builder() {{").unwrap();
    writeln!(out, "        return new {builder_name}();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // Static factory: from(record)
    writeln!(out, "    /**").unwrap();
    writeln!(
        out,
        "     * Create a builder pre-populated from an existing record."
    )
    .unwrap();
    writeln!(out, "     */").unwrap();
    writeln!(
        out,
        "    public static {builder_name} from({class_name} source) {{"
    )
    .unwrap();
    writeln!(out, "        {builder_name} b = new {builder_name}();").unwrap();
    for f in &all_fields {
        let java_name = to_camel_case(&f.name);
        let getter = avro_getter(&f.name);
        writeln!(out, "        b.{java_name} = source.{getter};").unwrap();
    }
    writeln!(out, "        return b;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // Fluent setter methods
    for f in &all_fields {
        let java_t = java_type(&f.field_type);
        let java_name = to_camel_case(&f.name);
        writeln!(
            out,
            "    public {builder_name} {java_name}({java_t} {java_name}) {{"
        )
        .unwrap();
        writeln!(out, "        this.{java_name} = {java_name};").unwrap();
        writeln!(out, "        return this;").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out).unwrap();
    }

    // build() method -- uses Avro builder
    writeln!(out, "    /**").unwrap();
    writeln!(
        out,
        "     * Build the {{@link {class_name}}} Avro record."
    )
    .unwrap();
    writeln!(out, "     */").unwrap();
    writeln!(out, "    public {class_name} build() {{").unwrap();
    writeln!(
        out,
        "        return {class_name}.newBuilder()"
    )
    .unwrap();
    for f in &all_fields {
        let java_name = to_camel_case(&f.name);
        let setter = avro_setter(&f.name);
        writeln!(out, "            .{setter}({java_name})").unwrap();
    }
    writeln!(out, "            .build();").unwrap();
    writeln!(out, "    }}").unwrap();

    // Close class
    writeln!(out, "}}").unwrap();

    (filename, out)
}

/// Avro SpecificRecord getter: `get` + PascalCase field name + `()`.
fn avro_getter(field_name: &str) -> String {
    format!("get{}()", to_pascal_case(field_name))
}

/// Avro SpecificRecord builder setter: `set` + PascalCase field name.
fn avro_setter(field_name: &str) -> String {
    format!("set{}", to_pascal_case(field_name))
}

fn collect_all_fields(schema: &SchemaDefinition) -> Vec<&FieldDecl> {
    let mut seen = std::collections::HashSet::new();
    let mut result = Vec::new();
    for f in &schema.identity {
        if seen.insert(&f.name) {
            result.push(f);
        }
    }
    for f in &schema.fields {
        if seen.insert(&f.name) {
            result.push(f);
        }
    }
    result
}

fn write_imports(out: &mut String, fields: &[&FieldDecl]) {
    let mut imports = std::collections::BTreeSet::new();
    for f in fields {
        for imp in super::types::java_imports_for_type(&f.field_type) {
            imports.insert(imp);
        }
    }
    for imp in imports {
        writeln!(out, "import {imp};").unwrap();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use nexflow_parser::ast::schema::*;

    fn make_field(name: &str, type_name: &str, required: bool) -> FieldDecl {
        FieldDecl {
            name: name.to_string(),
            field_type: FieldType::Base {
                name: type_name.to_string(),
                params: Vec::new(),
            },
            required,
            optional: !required,
            unique: false,
            cannot_change: false,
            encrypted: false,
            pii: None,
            default: None,
            deprecated: None,
            removal: None,
        }
    }

    fn make_schema() -> SchemaDefinition {
        SchemaDefinition {
            imports: Vec::new(),
            name: "account_detail".to_string(),
            patterns: Vec::new(),
            targets: Vec::new(),
            version: None,
            compatibility: None,
            retention: None,
            identity: vec![make_field("account_id", "uuid", true)],
            streaming: None,
            serialization: None,
            fields: vec![
                make_field("holder_name", "string", true),
                make_field("balance", "decimal", true),
                make_field("email", "string", false),
            ],
            nested_objects: Vec::new(),
            computed: Vec::new(),
            constraints: Vec::new(),
            immutable: None,
            state_machine: None,
            parameters: Vec::new(),
            entries: Vec::new(),
            rules: Vec::new(),
            migration: Vec::new(),
        }
    }

    #[test]
    fn test_builder_filename() {
        let (filename, _) = generate_builder(&make_schema());
        assert_eq!(filename, "AccountDetailBuilder.java");
    }

    #[test]
    fn test_builder_class_structure() {
        let (_, content) = generate_builder(&make_schema());

        assert!(content.contains("public final class AccountDetailBuilder {"));
        assert!(content.contains("public static AccountDetailBuilder builder()"));
        assert!(content.contains("public static AccountDetailBuilder from(AccountDetail source)"));
        assert!(content.contains("public AccountDetail build()"));
    }

    #[test]
    fn test_builder_fields() {
        let (_, content) = generate_builder(&make_schema());

        assert!(content.contains("private String accountId;"));
        assert!(content.contains("private String holderName;"));
        assert!(content.contains("private java.math.BigDecimal balance;"));
        assert!(content.contains("private String email;"));
    }

    #[test]
    fn test_builder_fluent_setters() {
        let (_, content) = generate_builder(&make_schema());

        assert!(content.contains("public AccountDetailBuilder accountId(String accountId)"));
        assert!(content.contains("public AccountDetailBuilder holderName(String holderName)"));
        assert!(content.contains("return this;"));
    }

    #[test]
    fn test_builder_from_copies() {
        let (_, content) = generate_builder(&make_schema());

        assert!(content.contains("b.accountId = source.getAccountId();"));
        assert!(content.contains("b.holderName = source.getHolderName();"));
        assert!(content.contains("b.balance = source.getBalance();"));
    }

    #[test]
    fn test_builder_build_calls_avro() {
        let (_, content) = generate_builder(&make_schema());

        assert!(content.contains("AccountDetail.newBuilder()"));
        assert!(content.contains(".setAccountId(accountId)"));
        assert!(content.contains(".setHolderName(holderName)"));
        assert!(content.contains(".build();"));
    }
}
