// MongoDB initialization script for Nex Platform
// Runs automatically when MongoDB container starts for the first time

db = db.getSiblingDB('nex');

// Create application user with readWrite permissions
db.createUser({
    user: 'nex_app',
    pwd: 'nex_app_dev',
    roles: [
        { role: 'readWrite', db: 'nex' }
    ]
});

// Transaction collection - receives data from Kafka Connect
db.createCollection('transactions', {
    validator: {
        $jsonSchema: {
            bsonType: 'object',
            required: ['transaction_id', 'customer_id', 'amount', 'event_timestamp'],
            properties: {
                transaction_id: { bsonType: 'string', description: 'Unique transaction identifier' },
                customer_id: { bsonType: 'string', description: 'Customer identifier' },
                amount: { bsonType: 'decimal', description: 'Transaction amount' },
                currency: { bsonType: 'string', maxLength: 3, description: 'Currency code (ISO 4217)' },
                merchant_id: { bsonType: 'string' },
                merchant_name: { bsonType: 'string' },
                category: { enum: ['retail', 'food', 'travel', 'entertainment', 'other'] },
                status: { enum: ['pending', 'approved', 'declined', 'fraud', 'refunded'] },
                risk_score: { bsonType: 'double', minimum: 0, maximum: 100 },
                event_timestamp: { bsonType: 'date' },
                processing_timestamp: { bsonType: 'date' },
                location: {
                    bsonType: 'object',
                    properties: {
                        country: { bsonType: 'string' },
                        city: { bsonType: 'string' },
                        postal_code: { bsonType: 'string' },
                        coordinates: { bsonType: 'array', items: { bsonType: 'double' } }
                    }
                }
            }
        }
    }
});

// Enriched transactions collection - processed by Flink
db.createCollection('enriched_transactions', {
    validator: {
        $jsonSchema: {
            bsonType: 'object',
            required: ['transaction_id', 'customer_id', 'amount', 'risk_tier'],
            properties: {
                transaction_id: { bsonType: 'string' },
                customer_id: { bsonType: 'string' },
                amount: { bsonType: 'decimal' },
                normalized_amount: { bsonType: 'decimal' },
                merchant_id: { bsonType: 'string' },
                risk_tier: { enum: ['low', 'medium', 'elevated', 'high', 'critical'] },
                credit_limit: { bsonType: 'decimal' },
                account_age: { bsonType: 'int' },
                velocity_24h: { bsonType: 'int' },
                fraud_probability: { bsonType: 'double' },
                fraud_action: { enum: ['approve', 'review', 'block', 'manual'] },
                event_timestamp: { bsonType: 'date' },
                processing_timestamp: { bsonType: 'date' }
            }
        }
    }
});

// Alerts collection - generated by Flink rules engine
db.createCollection('alerts', {
    validator: {
        $jsonSchema: {
            bsonType: 'object',
            required: ['alert_id', 'alert_type', 'severity', 'created_at'],
            properties: {
                alert_id: { bsonType: 'string' },
                alert_type: { enum: ['high_frequency', 'daily_limit', 'unusual_amount', 'combined_risk', 'fraud_detected'] },
                severity: { enum: ['info', 'warning', 'critical'] },
                transaction_id: { bsonType: 'string' },
                customer_id: { bsonType: 'string' },
                details: { bsonType: 'object' },
                created_at: { bsonType: 'date' },
                acknowledged: { bsonType: 'bool' },
                acknowledged_by: { bsonType: 'string' },
                acknowledged_at: { bsonType: 'date' }
            }
        }
    }
});

// Indexes
db.transactions.createIndex({ 'transaction_id': 1 }, { unique: true });
db.transactions.createIndex({ 'customer_id': 1 });
db.transactions.createIndex({ 'event_timestamp': -1 });
db.transactions.createIndex({ 'status': 1, 'event_timestamp': -1 });
db.transactions.createIndex({ 'merchant_id': 1, 'event_timestamp': -1 });

db.enriched_transactions.createIndex({ 'transaction_id': 1 }, { unique: true });
db.enriched_transactions.createIndex({ 'customer_id': 1, 'event_timestamp': -1 });
db.enriched_transactions.createIndex({ 'risk_tier': 1, 'event_timestamp': -1 });
db.enriched_transactions.createIndex({ 'fraud_action': 1, 'event_timestamp': -1 });

db.alerts.createIndex({ 'alert_id': 1 }, { unique: true });
db.alerts.createIndex({ 'customer_id': 1, 'created_at': -1 });
db.alerts.createIndex({ 'alert_type': 1, 'created_at': -1 });
db.alerts.createIndex({ 'severity': 1, 'acknowledged': 1 });
db.alerts.createIndex({ 'transaction_id': 1 });

// Auto-delete acknowledged alerts after 90 days
db.alerts.createIndex(
    { 'acknowledged_at': 1 },
    { expireAfterSeconds: 7776000, partialFilterExpression: { acknowledged: true } }
);

print('Nex MongoDB initialization complete!');
print('Collections: transactions, enriched_transactions, alerts');
