// NexCore -- Nexflow Codegen: Business Calendar Generator
// Copyright (c) 2024-2026 Chandra Mohn. All Rights Reserved.

//! Generates `BusinessCalendar.java` interface and `DefaultBusinessCalendar.java`.
//!
//! The interface is pluggable -- production deployments register a calendar
//! that knows about holidays, regional calendars, and settlement cycles.
//! The default implementation handles weekends only.

use std::fmt::Write;

const PACKAGE: &str = "com.nexflow.runtime";

/// Generate BusinessCalendar.java interface.
pub fn generate_business_calendar() -> (String, String) {
    let mut out = String::with_capacity(2048);

    writeln!(out, "package {PACKAGE};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import java.time.LocalDate;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/**").unwrap();
    writeln!(out, " * Business calendar interface for date calculations.").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * <p>Pluggable via {{@link NexflowRuntime#setBusinessCalendar(BusinessCalendar)}}.").unwrap();
    writeln!(out, " * Production implementations should account for:</p>").unwrap();
    writeln!(out, " * <ul>").unwrap();
    writeln!(out, " *   <li>Regional holidays (US, UK, etc.)</li>").unwrap();
    writeln!(out, " *   <li>Settlement cycles (T+1, T+2)</li>").unwrap();
    writeln!(out, " *   <li>Exchange-specific calendars</li>").unwrap();
    writeln!(out, " *   <li>Custom corporate calendars</li>").unwrap();
    writeln!(out, " * </ul>").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * <p>Generated by Nexflow Code Generator -- DO NOT EDIT.</p>").unwrap();
    writeln!(out, " */").unwrap();
    writeln!(out, "public interface BusinessCalendar {{").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    /** Get the current business date. */").unwrap();
    writeln!(out, "    LocalDate currentBusinessDate();").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    /** Check if a date is a business day. */").unwrap();
    writeln!(out, "    boolean isBusinessDay(LocalDate date);").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    /**").unwrap();
    writeln!(out, "     * Add N business days to a date (skipping non-business days).").unwrap();
    writeln!(out, "     * Negative values move backward.").unwrap();
    writeln!(out, "     */").unwrap();
    writeln!(out, "    LocalDate addBusinessDays(LocalDate date, int days);").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    /** Count business days between two dates (exclusive of end). */").unwrap();
    writeln!(out, "    long businessDaysBetween(LocalDate from, LocalDate to);").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    /** Get the next business day on or after the given date. */").unwrap();
    writeln!(out, "    default LocalDate nextBusinessDay(LocalDate date) {{").unwrap();
    writeln!(out, "        if (date == null) return null;").unwrap();
    writeln!(out, "        LocalDate d = date;").unwrap();
    writeln!(out, "        while (!isBusinessDay(d)) {{ d = d.plusDays(1); }}").unwrap();
    writeln!(out, "        return d;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    /** Get the previous business day on or before the given date. */").unwrap();
    writeln!(out, "    default LocalDate previousBusinessDay(LocalDate date) {{").unwrap();
    writeln!(out, "        if (date == null) return null;").unwrap();
    writeln!(out, "        LocalDate d = date;").unwrap();
    writeln!(out, "        while (!isBusinessDay(d)) {{ d = d.minusDays(1); }}").unwrap();
    writeln!(out, "        return d;").unwrap();
    writeln!(out, "    }}").unwrap();

    writeln!(out, "}}").unwrap();

    ("BusinessCalendar.java".to_string(), out)
}

/// Generate DefaultBusinessCalendar.java (weekends only).
pub fn generate_default_business_calendar() -> (String, String) {
    let mut out = String::with_capacity(2048);

    writeln!(out, "package {PACKAGE};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import java.time.DayOfWeek;").unwrap();
    writeln!(out, "import java.time.LocalDate;").unwrap();
    writeln!(out, "import java.time.ZoneOffset;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/**").unwrap();
    writeln!(out, " * Default business calendar: weekdays only (no holiday awareness).").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * <p>Replace with a holiday-aware implementation for production:</p>").unwrap();
    writeln!(out, " * <pre>").unwrap();
    writeln!(out, " * NexflowRuntime.setBusinessCalendar(new HolidayAwareCalendar(\"US\"));").unwrap();
    writeln!(out, " * </pre>").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * <p>Generated by Nexflow Code Generator -- DO NOT EDIT.</p>").unwrap();
    writeln!(out, " */").unwrap();
    writeln!(out, "public final class DefaultBusinessCalendar implements BusinessCalendar {{").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    @Override").unwrap();
    writeln!(out, "    public LocalDate currentBusinessDate() {{").unwrap();
    writeln!(out, "        LocalDate today = LocalDate.now(ZoneOffset.UTC);").unwrap();
    writeln!(out, "        return nextBusinessDay(today);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    @Override").unwrap();
    writeln!(out, "    public boolean isBusinessDay(LocalDate date) {{").unwrap();
    writeln!(out, "        if (date == null) return false;").unwrap();
    writeln!(out, "        DayOfWeek dow = date.getDayOfWeek();").unwrap();
    writeln!(out, "        return dow != DayOfWeek.SATURDAY && dow != DayOfWeek.SUNDAY;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    @Override").unwrap();
    writeln!(out, "    public LocalDate addBusinessDays(LocalDate date, int days) {{").unwrap();
    writeln!(out, "        if (date == null) return null;").unwrap();
    writeln!(out, "        LocalDate d = date;").unwrap();
    writeln!(out, "        int direction = days >= 0 ? 1 : -1;").unwrap();
    writeln!(out, "        int remaining = Math.abs(days);").unwrap();
    writeln!(out, "        while (remaining > 0) {{").unwrap();
    writeln!(out, "            d = d.plusDays(direction);").unwrap();
    writeln!(out, "            if (isBusinessDay(d)) remaining--;").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        return d;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    @Override").unwrap();
    writeln!(out, "    public long businessDaysBetween(LocalDate from, LocalDate to) {{").unwrap();
    writeln!(out, "        if (from == null || to == null) return 0;").unwrap();
    writeln!(out, "        long count = 0;").unwrap();
    writeln!(out, "        LocalDate start = from.isBefore(to) ? from : to;").unwrap();
    writeln!(out, "        LocalDate end = from.isBefore(to) ? to : from;").unwrap();
    writeln!(out, "        LocalDate d = start;").unwrap();
    writeln!(out, "        while (d.isBefore(end)) {{").unwrap();
    writeln!(out, "            if (isBusinessDay(d)) count++;").unwrap();
    writeln!(out, "            d = d.plusDays(1);").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "        return count;").unwrap();
    writeln!(out, "    }}").unwrap();

    writeln!(out, "}}").unwrap();

    ("DefaultBusinessCalendar.java".to_string(), out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_business_calendar_interface() {
        let (filename, content) = generate_business_calendar();
        assert_eq!(filename, "BusinessCalendar.java");
        assert!(content.contains("public interface BusinessCalendar"));
        assert!(content.contains("LocalDate currentBusinessDate()"));
        assert!(content.contains("boolean isBusinessDay(LocalDate date)"));
        assert!(content.contains("LocalDate addBusinessDays(LocalDate date, int days)"));
        assert!(content.contains("long businessDaysBetween(LocalDate from, LocalDate to)"));
        assert!(content.contains("default LocalDate nextBusinessDay("));
        assert!(content.contains("default LocalDate previousBusinessDay("));
    }

    #[test]
    fn test_default_calendar() {
        let (filename, content) = generate_default_business_calendar();
        assert_eq!(filename, "DefaultBusinessCalendar.java");
        assert!(content.contains("implements BusinessCalendar"));
        assert!(content.contains("DayOfWeek.SATURDAY"));
        assert!(content.contains("DayOfWeek.SUNDAY"));
        assert!(content.contains("nextBusinessDay(today)"));
    }

    #[test]
    fn test_calendar_handles_negative_days() {
        let (_, content) = generate_default_business_calendar();
        assert!(content.contains("int direction = days >= 0 ? 1 : -1"));
        assert!(content.contains("Math.abs(days)"));
    }

    #[test]
    fn test_calendar_pluggable_docs() {
        let (_, content) = generate_business_calendar();
        assert!(content.contains("NexflowRuntime#setBusinessCalendar"));
        assert!(content.contains("Regional holidays"));
        assert!(content.contains("Settlement cycles"));
    }
}
