// NexCore -- Nexflow Codegen: Lookup Infrastructure Generator
// Copyright (c) 2024-2026 Chandra Mohn. All Rights Reserved.

//! Generates `LookupService.java` interface and `LookupServiceFactory.java`.

use std::fmt::Write;

const PACKAGE: &str = "com.nexflow.runtime";

/// Generate LookupService.java interface.
pub fn generate_lookup_service() -> (String, String) {
    let mut out = String::with_capacity(2048);

    writeln!(out, "package {PACKAGE};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import java.util.concurrent.CompletableFuture;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/**").unwrap();
    writeln!(out, " * Generic lookup service interface for external data enrichment.").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * <p>Implementations connect to data stores (MongoDB, Redis, JDBC, etc.)").unwrap();
    writeln!(out, " * and provide key-value lookup semantics.</p>").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * <p>Contract:</p>").unwrap();
    writeln!(out, " * <ul>").unwrap();
    writeln!(out, " *   <li>Thread-safe for parallel Flink execution</li>").unwrap();
    writeln!(out, " *   <li>Returns null for cache misses (never throws for missing keys)</li>").unwrap();
    writeln!(out, " *   <li>Throws Exception only for I/O or infrastructure failures</li>").unwrap();
    writeln!(out, " *   <li>Implementations should be transient in Flink functions</li>").unwrap();
    writeln!(out, " * </ul>").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * <p>Generated by Nexflow Code Generator -- DO NOT EDIT.</p>").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * @param <T> the type of records returned by this service").unwrap();
    writeln!(out, " */").unwrap();
    writeln!(out, "public interface LookupService<T> {{").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    /**").unwrap();
    writeln!(out, "     * Synchronous lookup by key.").unwrap();
    writeln!(out, "     *").unwrap();
    writeln!(out, "     * @param key the lookup key (String, UUID, Long, or composite)").unwrap();
    writeln!(out, "     * @return the matching record, or null if not found").unwrap();
    writeln!(out, "     * @throws Exception on I/O or infrastructure failure").unwrap();
    writeln!(out, "     */").unwrap();
    writeln!(out, "    T lookup(Object key) throws Exception;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    /**").unwrap();
    writeln!(out, "     * Asynchronous lookup by key.").unwrap();
    writeln!(out, "     *").unwrap();
    writeln!(out, "     * <p>Default implementation wraps {{@link #lookup}} in a CompletableFuture.</p>").unwrap();
    writeln!(out, "     */").unwrap();
    writeln!(out, "    default CompletableFuture<T> lookupAsync(Object key) {{").unwrap();
    writeln!(out, "        return CompletableFuture.supplyAsync(() -> {{").unwrap();
    writeln!(out, "            try {{ return lookup(key); }}").unwrap();
    writeln!(out, "            catch (Exception e) {{ throw new RuntimeException(e); }}").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    /**").unwrap();
    writeln!(out, "     * Check if a key exists without fetching the full record.").unwrap();
    writeln!(out, "     */").unwrap();
    writeln!(out, "    default boolean exists(Object key) throws Exception {{").unwrap();
    writeln!(out, "        return lookup(key) != null;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    /**").unwrap();
    writeln!(out, "     * Release resources (connections, caches, etc.).").unwrap();
    writeln!(out, "     */").unwrap();
    writeln!(out, "    default void close() {{ /* no-op by default */ }}").unwrap();

    writeln!(out, "}}").unwrap();

    ("LookupService.java".to_string(), out)
}

/// Generate LookupServiceFactory.java.
pub fn generate_lookup_service_factory() -> (String, String) {
    let mut out = String::with_capacity(4096);

    writeln!(out, "package {PACKAGE};").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "import java.util.Map;").unwrap();
    writeln!(out, "import java.util.Objects;").unwrap();
    writeln!(out, "import java.util.concurrent.ConcurrentHashMap;").unwrap();
    writeln!(out, "import java.util.function.Function;").unwrap();
    writeln!(out, "import org.slf4j.Logger;").unwrap();
    writeln!(out, "import org.slf4j.LoggerFactory;").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "/**").unwrap();
    writeln!(out, " * Factory for creating and caching {{@link LookupService}} instances.").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * <p>Default behavior returns a no-op service that logs lookups and returns null.").unwrap();
    writeln!(out, " * Register custom factories for production data sources:</p>").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * <pre>").unwrap();
    writeln!(out, " * LookupServiceFactory.register(\"customer_profile\", name -> new MongoLookupService&lt;&gt;(name));").unwrap();
    writeln!(out, " * </pre>").unwrap();
    writeln!(out, " *").unwrap();
    writeln!(out, " * <p>Generated by Nexflow Code Generator -- DO NOT EDIT.</p>").unwrap();
    writeln!(out, " */").unwrap();
    writeln!(out, "public final class LookupServiceFactory {{").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    private static final Logger LOG = LoggerFactory.getLogger(LookupServiceFactory.class);").unwrap();
    writeln!(out).unwrap();

    // Registries
    writeln!(out, "    /** Cached service instances (thread-safe). */").unwrap();
    writeln!(out, "    private static final Map<String, LookupService<?>> instances = new ConcurrentHashMap<>();").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "    /** Registered factory functions per source name. */").unwrap();
    writeln!(out, "    private static final Map<String, Function<String, LookupService<?>>> factories = new ConcurrentHashMap<>();").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "    private LookupServiceFactory() {{}}").unwrap();
    writeln!(out).unwrap();

    // register()
    writeln!(out, "    /**").unwrap();
    writeln!(out, "     * Register a factory for a specific source name.").unwrap();
    writeln!(out, "     *").unwrap();
    writeln!(out, "     * @param sourceName the data source identifier (e.g. \"customer_profile\")").unwrap();
    writeln!(out, "     * @param factory function that creates a LookupService for this source").unwrap();
    writeln!(out, "     */").unwrap();
    writeln!(out, "    public static void register(String sourceName, Function<String, LookupService<?>> factory) {{").unwrap();
    writeln!(out, "        Objects.requireNonNull(sourceName, \"sourceName\");").unwrap();
    writeln!(out, "        Objects.requireNonNull(factory, \"factory\");").unwrap();
    writeln!(out, "        factories.put(sourceName, factory);").unwrap();
    writeln!(out, "        instances.remove(sourceName); // Clear cached instance").unwrap();
    writeln!(out, "        LOG.info(\"Registered lookup factory for: {{}}\", sourceName);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // create()
    writeln!(out, "    /**").unwrap();
    writeln!(out, "     * Create or retrieve a cached LookupService for the given source.").unwrap();
    writeln!(out, "     *").unwrap();
    writeln!(out, "     * <p>If no factory is registered, returns a no-op service that logs and returns null.</p>").unwrap();
    writeln!(out, "     */").unwrap();
    writeln!(out, "    @SuppressWarnings(\"unchecked\")").unwrap();
    writeln!(out, "    public static <T> LookupService<T> create(String sourceName) {{").unwrap();
    writeln!(out, "        return (LookupService<T>) instances.computeIfAbsent(sourceName, name -> {{").unwrap();
    writeln!(out, "            Function<String, LookupService<?>> factory = factories.get(name);").unwrap();
    writeln!(out, "            if (factory != null) {{").unwrap();
    writeln!(out, "                LOG.info(\"Creating lookup service for: {{}}\", name);").unwrap();
    writeln!(out, "                return factory.apply(name);").unwrap();
    writeln!(out, "            }}").unwrap();
    writeln!(out, "            LOG.warn(\"No factory registered for '{{}}' -- using no-op lookup\", name);").unwrap();
    writeln!(out, "            return new NoOpLookupService<>(name);").unwrap();
    writeln!(out, "        }});").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // reset()
    writeln!(out, "    /** Clear all cached instances and registered factories (for testing). */").unwrap();
    writeln!(out, "    public static void reset() {{").unwrap();
    writeln!(out, "        instances.values().forEach(LookupService::close);").unwrap();
    writeln!(out, "        instances.clear();").unwrap();
    writeln!(out, "        factories.clear();").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out).unwrap();

    // NoOpLookupService inner class
    writeln!(out, "    /** No-op implementation that logs lookups and returns null. */").unwrap();
    writeln!(out, "    private static final class NoOpLookupService<T> implements LookupService<T> {{").unwrap();
    writeln!(out, "        private final String sourceName;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "        NoOpLookupService(String sourceName) {{ this.sourceName = sourceName; }}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "        @Override").unwrap();
    writeln!(out, "        public T lookup(Object key) {{").unwrap();
    writeln!(out, "            LOG.debug(\"No-op lookup on '{{}}' with key: {{}}\", sourceName, key);").unwrap();
    writeln!(out, "            return null;").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "        @Override").unwrap();
    writeln!(out, "        public String toString() {{").unwrap();
    writeln!(out, "            return \"NoOpLookupService[\" + sourceName + \"]\";").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();

    writeln!(out, "}}").unwrap();

    ("LookupServiceFactory.java".to_string(), out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lookup_service_interface() {
        let (filename, content) = generate_lookup_service();
        assert_eq!(filename, "LookupService.java");
        assert!(content.contains("public interface LookupService<T>"));
        assert!(content.contains("T lookup(Object key) throws Exception"));
        assert!(content.contains("CompletableFuture<T> lookupAsync(Object key)"));
        assert!(content.contains("default boolean exists(Object key)"));
        assert!(content.contains("default void close()"));
    }

    #[test]
    fn test_lookup_factory() {
        let (filename, content) = generate_lookup_service_factory();
        assert_eq!(filename, "LookupServiceFactory.java");
        assert!(content.contains("public final class LookupServiceFactory"));
        assert!(content.contains("public static void register(String sourceName"));
        assert!(content.contains("public static <T> LookupService<T> create(String sourceName)"));
        assert!(content.contains("public static void reset()"));
        assert!(content.contains("class NoOpLookupService<T> implements LookupService<T>"));
    }

    #[test]
    fn test_factory_uses_concurrent_maps() {
        let (_, content) = generate_lookup_service_factory();
        assert!(content.contains("ConcurrentHashMap"));
        assert!(content.contains("computeIfAbsent"));
    }

    #[test]
    fn test_factory_has_register_pattern() {
        let (_, content) = generate_lookup_service_factory();
        assert!(content.contains("Function<String, LookupService<?>> factory"));
        assert!(content.contains("factories.put(sourceName, factory)"));
        assert!(content.contains("instances.remove(sourceName)"));
    }
}
