//! Plan file generation for Tier 3 structural assessment.
//!
//! Generates `rustify/plan.md` with structural analysis, recommended
//! decomposition phases, dependency order, and estimated effort.

use std::io::Write;
use std::path::Path;

use crate::error::RustifyError;
use crate::rules::transform::{Safety, Transform};

/// Write plan.md from Tier 3 assessment transforms.
pub fn write_plan(
    output_dir: &Path,
    transforms: &[Transform],
    tier: u8,
) -> Result<(), RustifyError> {
    let assessments: Vec<_> = transforms
        .iter()
        .filter(|t| matches!(t.safety, Safety::Assessment))
        .collect();

    if assessments.is_empty() {
        return Ok(());
    }

    let rustify_dir = output_dir.join("rustify");
    std::fs::create_dir_all(&rustify_dir)?;

    let mut f = std::fs::File::create(rustify_dir.join("plan.md"))?;
    write_plan_content(&mut f, &assessments, tier)?;

    Ok(())
}

fn write_plan_content<W: Write>(
    w: &mut W,
    items: &[&Transform],
    tier: u8,
) -> std::io::Result<()> {
    writeln!(w, "# Rustify Structural Assessment -- Tier {tier}")?;
    writeln!(w)?;
    writeln!(w, "This plan was generated by `cobol2rust rustify --tier 3`.")?;
    writeln!(w, "It contains structural analysis and recommendations for")?;
    writeln!(w, "transforming COBOL-shaped Rust into idiomatic Rust.")?;
    writeln!(w)?;
    writeln!(w, "**No changes were applied.** This is an assessment only.")?;
    writeln!(w)?;

    // Group by rule
    let mut by_rule: std::collections::HashMap<&str, Vec<&&Transform>> =
        std::collections::HashMap::new();
    for item in items {
        by_rule.entry(item.rule_id.as_str()).or_default().push(item);
    }

    // Order rules in recommended execution order
    let rule_order = [
        "dispatcher-analysis",
        "ws-decomposition",
        "status-to-result",
        "io-modernize",
    ];

    writeln!(w, "## Summary")?;
    writeln!(w)?;
    writeln!(w, "| Phase | Analysis | Items |")?;
    writeln!(w, "|-------|----------|-------|")?;

    for (i, rule_id) in rule_order.iter().enumerate() {
        if let Some(rule_items) = by_rule.get(rule_id) {
            let phase_name = rule_to_phase_name(rule_id);
            writeln!(w, "| {} | {} | {} |", i + 1, phase_name, rule_items.len())?;
        }
    }
    // Include any rules not in the predefined order
    for (rule_id, rule_items) in &by_rule {
        if !rule_order.contains(rule_id) {
            let phase_name = rule_to_phase_name(rule_id);
            writeln!(w, "| - | {} | {} |", phase_name, rule_items.len())?;
        }
    }
    writeln!(w)?;

    // Recommended phases
    writeln!(w, "## Recommended Phases")?;
    writeln!(w)?;

    let mut phase_num = 1;
    for rule_id in &rule_order {
        if let Some(rule_items) = by_rule.get(rule_id) {
            let phase_name = rule_to_phase_name(rule_id);
            let effort = estimate_effort(rule_id, rule_items.len());
            let deps = phase_dependencies(rule_id);

            writeln!(w, "### Phase {phase_num}: {phase_name}")?;
            writeln!(w)?;
            writeln!(w, "**Estimated effort**: {effort}")?;
            if !deps.is_empty() {
                writeln!(w, "**Depends on**: {deps}")?;
            }
            writeln!(w)?;

            for item in rule_items {
                writeln!(w, "- {}", item.description)?;
            }
            writeln!(w)?;
            phase_num += 1;
        }
    }

    // Dependency graph
    writeln!(w, "## Dependency Order")?;
    writeln!(w)?;
    writeln!(w, "```")?;
    writeln!(w, "Phase 1: Dispatcher Analysis (understand control flow first)")?;
    writeln!(w, "  |")?;
    writeln!(w, "  v")?;
    writeln!(w, "Phase 2: WorkingStorage Decomposition (group related data)")?;
    writeln!(w, "  |")?;
    writeln!(w, "  v")?;
    writeln!(w, "Phase 3: Status-to-Result (convert return codes)")?;
    writeln!(w, "  |")?;
    writeln!(w, "  v")?;
    writeln!(w, "Phase 4: I/O Modernization (replace file I/O patterns)")?;
    writeln!(w, "```")?;
    writeln!(w)?;

    writeln!(w, "## Next Steps")?;
    writeln!(w)?;
    writeln!(w, "1. Review each phase's findings above")?;
    writeln!(w, "2. Start with Phase 1 (dispatcher) to understand the program structure")?;
    writeln!(w, "3. Use Phase 2 findings to plan struct decomposition")?;
    writeln!(w, "4. Apply phases in dependency order")?;
    writeln!(w, "5. Run `cargo check` after each phase to verify correctness")?;

    Ok(())
}

fn rule_to_phase_name(rule_id: &str) -> &'static str {
    match rule_id {
        "dispatcher-analysis" => "Dispatcher Analysis",
        "ws-decomposition" => "WorkingStorage Decomposition",
        "status-to-result" => "Status-to-Result Mapping",
        "io-modernize" => "I/O Modernization",
        _ => "Custom Analysis",
    }
}

fn estimate_effort(rule_id: &str, item_count: usize) -> String {
    match rule_id {
        "dispatcher-analysis" => {
            if item_count > 0 {
                "1-2 hours (understand control flow)".to_string()
            } else {
                "minimal".to_string()
            }
        }
        "ws-decomposition" => format!(
            "{}-{} hours (per sub-struct proposal)",
            item_count,
            item_count * 2
        ),
        "status-to-result" => format!(
            "{} hour(s) ({} status field(s))",
            item_count.div_ceil(2),
            item_count
        ),
        "io-modernize" => format!(
            "{}-{} hours ({} file handle(s))",
            item_count,
            item_count * 3,
            item_count
        ),
        _ => format!("{item_count} item(s)"),
    }
}

fn phase_dependencies(rule_id: &str) -> &'static str {
    match rule_id {
        "ws-decomposition" => "Phase 1 (Dispatcher Analysis)",
        "status-to-result" | "io-modernize" => "Phase 2 (WorkingStorage Decomposition)",
        _ => "",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn empty_plan_no_file() {
        let dir = std::env::temp_dir().join("cobol2rust_test_plan_empty");
        let _ = std::fs::create_dir_all(&dir);
        write_plan(&dir, &[], 3).unwrap();
        assert!(!dir.join("rustify").join("plan.md").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn plan_with_assessments() {
        let transforms = vec![
            Transform {
                rule_id: "dispatcher-analysis".to_string(),
                file: PathBuf::from("src/main.rs"),
                line: 0,
                description: "Dispatch analysis: 15 paragraphs, max depth 4".to_string(),
                safety: Safety::Assessment,
                edits: vec![],
            },
            Transform {
                rule_id: "ws-decomposition".to_string(),
                file: PathBuf::from("src/main.rs"),
                line: 0,
                description: "WorkingStorage: 45 fields, 3 sub-struct(s) proposed".to_string(),
                safety: Safety::Assessment,
                edits: vec![],
            },
            Transform {
                rule_id: "io-modernize".to_string(),
                file: PathBuf::from("src/main.rs"),
                line: 0,
                description: "2 file handle(s) -- input_file: sequential read, output_file: sequential write".to_string(),
                safety: Safety::Assessment,
                edits: vec![],
            },
        ];

        let mut buf = Vec::new();
        let items: Vec<_> = transforms.iter().collect();
        write_plan_content(&mut buf, &items, 3).unwrap();
        let text = String::from_utf8(buf).unwrap();

        assert!(text.contains("Tier 3"));
        assert!(text.contains("Dispatcher Analysis"));
        assert!(text.contains("WorkingStorage Decomposition"));
        assert!(text.contains("I/O Modernization"));
        assert!(text.contains("Dependency Order"));
        assert!(text.contains("Next Steps"));
        assert!(text.contains("Phase 1"));
    }

    #[test]
    fn plan_skips_auto_transforms() {
        let transforms = vec![Transform {
            rule_id: "zero-literal".to_string(),
            file: PathBuf::from("src/main.rs"),
            line: 5,
            description: "replace zero literal".to_string(),
            safety: Safety::Auto,
            edits: vec![],
        }];

        let dir = std::env::temp_dir().join("cobol2rust_test_plan_skip_auto");
        let _ = std::fs::create_dir_all(&dir);
        write_plan(&dir, &transforms, 3).unwrap();
        assert!(!dir.join("rustify").join("plan.md").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
