//! EXEC SQL -> schema extraction from SQL statements.
//!
//! When a COBOL program uses EXEC SQL, the relational schema already exists.
//! This module extracts table names and column mappings from SQL statements
//! and host variable references to produce schemas that mirror the DB2 tables.

use std::collections::{BTreeMap, BTreeSet};

use cobol_transpiler::ast::{ExecSqlStatement, SqlStatementType};

use crate::dsl::dsl_ast::*;
use crate::dsl::DslFile;

/// An extracted SQL table with its columns.
struct SqlTable {
    /// Table name (from SQL).
    table_name: String,
    /// Columns seen in SELECT INTO / INSERT / UPDATE (host var names).
    columns: BTreeSet<String>,
    /// Whether this table has SELECT (read) access.
    has_select: bool,
    /// Whether this table has INSERT/UPDATE/DELETE (write) access.
    has_write: bool,
}

/// Extract schemas from EXEC SQL statements in a program.
///
/// Each SQL table referenced becomes a .schema file.
/// Host variables map to column names.
pub fn extract_sql_schemas(
    sql_stmts: &[ExecSqlStatement],
    program: &str,
) -> Vec<DslFile> {
    if sql_stmts.is_empty() {
        return vec![];
    }

    // Collect table -> columns from all SQL statements
    let mut tables: BTreeMap<String, SqlTable> = BTreeMap::new();

    for stmt in sql_stmts {
        let table_name = extract_table_name(&stmt.raw_sql);
        if table_name.is_empty() {
            continue;
        }

        let entry = tables.entry(table_name.clone()).or_insert_with(|| SqlTable {
            table_name: table_name.clone(),
            columns: BTreeSet::new(),
            has_select: false,
            has_write: false,
        });

        // Collect host variables as column proxies
        for var in &stmt.output_vars {
            entry.columns.insert(var.field_name.clone());
        }
        for var in &stmt.input_vars {
            entry.columns.insert(var.field_name.clone());
        }

        match stmt.sql_type {
            SqlStatementType::SelectInto | SqlStatementType::FetchCursor => {
                entry.has_select = true;
            }
            SqlStatementType::Insert
            | SqlStatementType::Update
            | SqlStatementType::Delete => {
                entry.has_write = true;
            }
            _ => {}
        }
    }

    // Generate one .schema per SQL table
    let mut dsl_files = Vec::new();

    for (_, table) in &tables {
        if table.columns.is_empty() {
            continue;
        }

        let schema_name = table.table_name.to_lowercase().replace('-', "_");

        let fields: Vec<FieldDecl> = table
            .columns
            .iter()
            .map(|col| {
                let snake = col.to_lowercase().replace('-', "_");
                FieldDecl {
                    name: Ident::new(&snake),
                    field_type: FieldType::String(None), // Type comes from DDL, not COBOL
                    required: true,
                    comment: Some(format!("DB2 host variable: {col}")),
                }
            })
            .collect();

        // First column of SELECT INTO is often the key
        let identity = fields.first().map(|f| {
            vec![FieldDecl {
                name: f.name.clone(),
                field_type: f.field_type.clone(),
                required: true,
                comment: None,
            }]
        });

        let mut notes = vec![
            format!(
                "DB2 table: {} ({} columns from host variables)",
                table.table_name,
                table.columns.len()
            ),
        ];
        if table.has_select {
            notes.push("Access: SELECT (read)".to_string());
        }
        if table.has_write {
            notes.push("Access: INSERT/UPDATE/DELETE (write)".to_string());
        }
        notes.push(
            "Column types are placeholders -- actual types come from DB2 catalog DDL".to_string(),
        );

        let schema_file = SchemaFile {
            comments: vec![
                Comment("Generated by cobol2rust Nexflow emitter".to_string()),
                Comment(format!("DB2 table: {}", table.table_name)),
                Comment(format!("Source: {program} (EXEC SQL)")),
                Comment("NOTE: Column types are host-variable based. Import DDL for exact types.".to_string()),
            ],
            imports: vec![],
            schemas: vec![SchemaDef {
                name: Ident::new(&schema_name),
                pattern: Some(super::schema_pattern::detect_pattern_for_sql()),
                identity,
                fields,
                nested_objects: vec![],
                constraints: vec![],
            }],
        };

        dsl_files.push(DslFile {
            path: format!("schema/db2_{schema_name}.schema"),
            content: schema_file.to_text(),
            confidence: 0.8, // Types are approximate (from host vars, not DDL)
            notes,
            source_fields: table.columns.iter().cloned().collect(),
        });
    }

    dsl_files
}

/// Extract table name from raw SQL text.
/// Handles: SELECT ... FROM table, INSERT INTO table, UPDATE table, DELETE FROM table.
fn extract_table_name(raw_sql: &str) -> String {
    let upper = raw_sql.to_uppercase();
    let tokens: Vec<&str> = upper.split_whitespace().collect();

    // SELECT ... FROM table
    if let Some(pos) = tokens.iter().position(|&t| t == "FROM") {
        if let Some(name) = tokens.get(pos + 1) {
            return clean_table_name(name);
        }
    }

    // INSERT INTO table
    if let Some(pos) = tokens.iter().position(|&t| t == "INTO") {
        // Skip "SELECT INTO" (that's host vars, not a table)
        if pos > 0 && tokens.get(pos - 1) != Some(&"SELECT") {
            if let Some(name) = tokens.get(pos + 1) {
                return clean_table_name(name);
            }
        }
    }

    // UPDATE table SET ...
    if tokens.first() == Some(&"UPDATE") {
        if let Some(name) = tokens.get(1) {
            return clean_table_name(name);
        }
    }

    // DELETE FROM table
    if tokens.first() == Some(&"DELETE") {
        if let Some(pos) = tokens.iter().position(|&t| t == "FROM") {
            if let Some(name) = tokens.get(pos + 1) {
                return clean_table_name(name);
            }
        }
    }

    String::new()
}

/// Clean a table name: remove schema prefix, parentheses, etc.
fn clean_table_name(name: &str) -> String {
    let cleaned = name
        .trim_end_matches('(')
        .trim_end_matches(',')
        .trim_end_matches(';');

    // Handle schema.table format: take the table part
    if let Some(pos) = cleaned.rfind('.') {
        cleaned[pos + 1..].to_string()
    } else {
        cleaned.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use cobol_transpiler::ast::HostVarRef;

    fn make_sql(
        sql_type: SqlStatementType,
        raw_sql: &str,
        input: Vec<&str>,
        output: Vec<&str>,
    ) -> ExecSqlStatement {
        ExecSqlStatement {
            sql_type,
            raw_sql: raw_sql.to_string(),
            input_vars: input
                .into_iter()
                .map(|v| HostVarRef {
                    field_name: v.to_string(),
                    indicator: None,
                })
                .collect(),
            output_vars: output
                .into_iter()
                .map(|v| HostVarRef {
                    field_name: v.to_string(),
                    indicator: None,
                })
                .collect(),
            cursor_name: None,
            prepared_name: None,
        }
    }

    #[test]
    fn extract_table_from_select() {
        assert_eq!(
            extract_table_name("SELECT ACCT_NUM, ACCT_NAME FROM ACCOUNT_TABLE WHERE ACCT_NUM = :WS-ACCT"),
            "ACCOUNT_TABLE"
        );
    }

    #[test]
    fn extract_table_from_insert() {
        assert_eq!(
            extract_table_name("INSERT INTO TRANS_LOG (TXN_ID, TXN_AMT) VALUES (:WS-ID, :WS-AMT)"),
            "TRANS_LOG"
        );
    }

    #[test]
    fn extract_table_from_update() {
        assert_eq!(
            extract_table_name("UPDATE CUSTOMER SET STATUS = :WS-STATUS WHERE CUST_ID = :WS-ID"),
            "CUSTOMER"
        );
    }

    #[test]
    fn extract_table_with_schema_prefix() {
        assert_eq!(
            extract_table_name("SELECT COL1 FROM MYSCHEMA.MYTABLE WHERE X = :Y"),
            "MYTABLE"
        );
    }

    #[test]
    fn sql_produces_schema() {
        let stmts = vec![make_sql(
            SqlStatementType::SelectInto,
            "SELECT ACCT_NUM, ACCT_NAME, BALANCE FROM ACCOUNT WHERE ACCT_NUM = :WS-ACCT-NUM",
            vec!["WS-ACCT-NUM"],
            vec!["WS-ACCT-NUM", "WS-ACCT-NAME", "WS-BALANCE"],
        )];

        let files = extract_sql_schemas(&stmts, "TESTPROG");
        assert_eq!(files.len(), 1);
        assert!(files[0].path.contains("db2_account"), "Path: {}", files[0].path);

        let content = &files[0].content;
        assert!(content.contains("DB2 table"), "Content: {content}");
        assert!(content.contains("ws_acct_num"), "Content: {content}");
        assert!(content.contains("ws_balance"), "Content: {content}");
    }

    #[test]
    fn no_sql_produces_nothing() {
        let files = extract_sql_schemas(&[], "TESTPROG");
        assert!(files.is_empty());
    }
}
