//! REDEFINES -> variant schema extraction.
//!
//! Each REDEFINES group produces a separate .schema per variant view,
//! plus a discriminator annotation on the parent schema.
//! Reuses cobol-data types for discriminator detection.

use cobol_transpiler::ast::DataEntry;

use crate::dsl::dsl_ast::*;
use crate::dsl::DslFile;

use super::cobol_extract::cobol_name_to_snake;
use super::schema_fields::{flatten_children, is_filler};

/// Extracted variant schema from a REDEFINES group.
#[derive(Debug)]
pub struct RedefinesSchema {
    /// The generated DslFile for the variant schema.
    pub dsl_file: DslFile,
    /// Annotation for the parent schema (comment about the REDEFINES).
    pub parent_annotation: String,
    /// The base field name being redefined.
    pub base_field: String,
}

/// Extract variant schemas from REDEFINES entries within a list of children.
///
/// `parent_name` is the schema name of the parent entity.
/// `program` is the program name for comments.
pub fn extract_redefines_schemas(
    children: &[DataEntry],
    parent_name: &str,
    program: &str,
) -> Vec<RedefinesSchema> {
    let mut results = Vec::new();

    for child in children {
        if child.redefines.is_none() || is_filler(&child.name) {
            continue;
        }

        let variant_name = cobol_name_to_snake(&child.name);
        let base_field = child.redefines.as_deref().unwrap_or("UNKNOWN");
        let base_snake = cobol_name_to_snake(base_field);

        let mut fields = Vec::new();
        let mut constraints = Vec::new();

        if child.children.is_empty() {
            // Elementary REDEFINES -- just the field itself
            if let Some(field) = super::schema_fields::entry_to_field_decl(child) {
                fields.push(field);
            }
        } else {
            // Group REDEFINES -- flatten children
            flatten_children(&child.children, &mut fields, &mut constraints);
        }

        // Look for discriminator hints in sibling level-88 conditions
        // on the base field's parent or siblings
        let discriminator_hint = find_discriminator_hint(children, base_field);

        let mut notes = vec![
            format!("REDEFINES: {} redefines {}", child.name, base_field),
        ];
        if let Some(ref hint) = discriminator_hint {
            notes.push(format!("Discriminator candidate: {}", hint));
        }

        let schema_file = SchemaFile {
            comments: vec![
                Comment("Generated by cobol2rust Nexflow emitter".to_string()),
                Comment(format!(
                    "REDEFINES variant: {} redefines {}",
                    child.name, base_field
                )),
                Comment(format!("Parent schema: {parent_name}")),
                Comment(format!("Source: {program}")),
            ],
            imports: vec![],
            schemas: vec![SchemaDef {
                name: Ident::new(&variant_name),
                pattern: Some(MutationPattern::MasterData),
                identity: None, // Shares PK with parent (1:1 FK)
                fields,
                nested_objects: vec![],
                constraints,
            }],
        };

        let parent_note = if let Some(ref disc) = discriminator_hint {
            format!(
                "// REDEFINES: {base_snake} -> see {variant_name}.schema (discriminator: {disc})",
            )
        } else {
            format!(
                "// REDEFINES: {base_snake} -> see {variant_name}.schema (discriminator: UNRESOLVED)",
            )
        };

        results.push(RedefinesSchema {
            dsl_file: DslFile {
                path: format!("schema/{variant_name}.schema"),
                content: schema_file.to_text(),
                confidence: if discriminator_hint.is_some() { 0.9 } else { 0.7 },
                notes,
                source_fields: vec![child.name.clone()],
            },
            parent_annotation: parent_note,
            base_field: base_field.to_string(),
        });
    }

    results
}

/// Look for a discriminator hint by scanning siblings for level-88 conditions
/// near the base field. A field with 88-level children adjacent to the REDEFINES
/// base is likely the discriminator.
fn find_discriminator_hint(siblings: &[DataEntry], base_field: &str) -> Option<String> {
    let base_upper = base_field.to_uppercase();

    // Strategy: find fields near (before) the base field that have level-88 children.
    // In COBOL, the discriminator typically appears just before the REDEFINES block.
    let mut candidate: Option<String> = None;

    for sibling in siblings {
        if sibling.name.to_uppercase() == base_upper {
            // Reached the base field -- the candidate (if any) is our best guess
            break;
        }

        // Check if this sibling has level-88 children (enum values)
        let has_88 = sibling.children.iter().any(|c| c.level == 88)
            || !sibling.condition_values.is_empty();

        if has_88 && sibling.pic.is_some() {
            // This field has enum values -- likely discriminator
            candidate = Some(cobol_name_to_snake(&sibling.name));
        }
    }

    candidate
}

#[cfg(test)]
mod tests {
    use super::*;
    use cobol_transpiler::ast::{
        ConditionValue, DataEntry, Literal as CobolLiteral, PicCategory, PicClause, Usage,
    };

    fn make_entry(name: &str, pic_raw: &str, level: u8) -> DataEntry {
        DataEntry {
            level, name: name.to_string(),
            pic: Some(PicClause {
                raw: pic_raw.to_string(),
                category: PicCategory::Alphanumeric,
                total_digits: 10, scale: 0, signed: false, display_length: 10,
                edit_symbols: vec![],
            }),
            usage: Usage::Display, value: None, redefines: None,
            occurs: None, occurs_depending: None, sign: None,
            justified_right: false, blank_when_zero: false,
            children: vec![], condition_values: vec![],
            byte_offset: None, byte_length: None,
            renames_target: None, renames_thru: None, index_names: vec![],
        }
    }

    #[test]
    fn redefines_produces_variant_schema() {
        let base = make_entry("WS-PAY-DETAILS", "X(50)", 5);
        let mut variant = DataEntry {
            level: 5,
            name: "WS-CHECK-DETAIL".to_string(),
            pic: None, usage: Usage::Display, value: None,
            redefines: Some("WS-PAY-DETAILS".to_string()),
            occurs: None, occurs_depending: None, sign: None,
            justified_right: false, blank_when_zero: false,
            children: vec![
                make_entry("WS-CHECK-NUMBER", "X(10)", 10),
                make_entry("WS-CHECK-BANK", "X(20)", 10),
            ],
            condition_values: vec![], byte_offset: None, byte_length: None,
            renames_target: None, renames_thru: None, index_names: vec![],
        };

        let children = vec![base, variant];
        let results = extract_redefines_schemas(&children, "ws_payment", "TEST");

        assert_eq!(results.len(), 1);
        assert_eq!(results[0].dsl_file.path, "schema/ws_check_detail.schema");

        let content = &results[0].dsl_file.content;
        assert!(content.contains("REDEFINES"), "Content: {content}");
        assert!(content.contains("ws_check_number"), "Content: {content}");
        assert!(content.contains("ws_check_bank"), "Content: {content}");
    }

    #[test]
    fn discriminator_hint_from_88_levels() {
        let mut disc_field = make_entry("WS-PAY-TYPE", "X(1)", 5);
        disc_field.children.push(DataEntry {
            level: 88, name: "WS-PAY-CHECK".to_string(),
            pic: None, usage: Usage::Display, value: None, redefines: None,
            occurs: None, occurs_depending: None, sign: None,
            justified_right: false, blank_when_zero: false,
            children: vec![],
            condition_values: vec![ConditionValue::Single(CobolLiteral::Alphanumeric("C".to_string()))],
            byte_offset: None, byte_length: None,
            renames_target: None, renames_thru: None, index_names: vec![],
        });

        let base = make_entry("WS-PAY-DETAILS", "X(50)", 5);
        let mut variant = DataEntry {
            level: 5, name: "WS-CHECK-VIEW".to_string(),
            pic: None, usage: Usage::Display, value: None,
            redefines: Some("WS-PAY-DETAILS".to_string()),
            occurs: None, occurs_depending: None, sign: None,
            justified_right: false, blank_when_zero: false,
            children: vec![make_entry("WS-CHK-NUM", "X(10)", 10)],
            condition_values: vec![], byte_offset: None, byte_length: None,
            renames_target: None, renames_thru: None, index_names: vec![],
        };

        let children = vec![disc_field, base, variant];
        let results = extract_redefines_schemas(&children, "ws_payment", "TEST");

        assert_eq!(results.len(), 1);
        assert!(
            results[0].parent_annotation.contains("ws_pay_type"),
            "Should detect discriminator: {}",
            results[0].parent_annotation
        );
    }
}
